### ISSUE TITLE
Astroncia IPTV error

### ISSUE THREAD

**Issue by ciorci** [superolmo/pyxtream#1]
When Astroncia is loading, I get this error

Traceback (most recent call last):
  File "/usr/lib/astronciaiptv/./astroncia_iptv.py", line 841, in <module>
    xt.load_iptv()
  File "/usr/lib/astronciaiptv/thirdparty/xtream.py", line 584, in load_iptv
    if stream_channel['name'][0].isalnum():
IndexError: string index out of range

The developer says the error is related to XTream API library, not Astroncia IPTV itself.
I'm on Archlinux with Vstreams IPTV subscription

**Comment by superolmo** [comment]
It looks like the stream channel name is not an array with your provider. Since I cannot get access to your provider for testing, the best thing to do is for you to modify the code and troubleshoot it together. Do you feel comfortable doing so?
By the way, do you have an open issue with Astroncia IPTV?

**Comment by ciorci** [comment]
if it can be useful I can request a trial for you from my provider, so that you can see the whole list of channels. The only requirement is a VPN if you live in Europe. I don't know if I can help you with testing the code changes, but I can try. I don't have an open issue with Astroncia IPTV. I wrote to the developer at the address indicated in the error window. He replied: 
" It's issue with XTream API library, not Astroncia IPTV itself. Please create issue here https://github.com/superolmo/pyxtream/issue ".

**Comment by superolmo** [comment]
Yes, a trial would be helpful to check their data format. I can find a VPN if necessary, I am in the USA.
If I fix it on my side, who is going to update their copy?

**Comment by ciorci** [comment]
I requested the trial period at my provider, let me know how I can provide you  the login details. Then I will contact the developer of Astroncia to know how to implement a possible solution.

**Comment by superolmo** [comment]
Once I can troubleshoot the issue, I will be updating the main pyxtream library. With that, you can open an issue and let the developers know that there has been an update that fixed your problem. Most likely it will take few days or weeks before the developers can integrate the update in their release. Or you can just swap the specific file in your file system.

**Comment by ciorci** [comment]
the Anstroncia developer say:
" please ask pyxtream developer to update this file https://github.com/superolmo/hypnotix/blob/master/usr/lib/hypnotix/xtream.py when main pyxtream library is updated "
Please I need a private address to send you the trial data.

**Comment by superolmo** [comment]
Please send to superolmo2 at gmail

**Comment by superolmo** [comment]
I have updated [https://github.com/superolmo/hypnotix/blob/master/usr/lib/hypnotix/xtream.py](https://github.com/superolmo/hypnotix/blob/master/usr/lib/hypnotix/xtream.py)

**Comment by ciorci** [comment]
it works! thanks. 
Astronciaiptv has already been updated.
