### ISSUE TITLE
Sleep function seemingly delaying initial requests unnecessarily

### ISSUE THREAD

**Issue by po1xi548Rysh8BH6** [superolmo/pyxtream#11]
I'm not sure how to create a PR (I don't use GitHub) but would you be willing to move this delay from line 952 to line 973? This change potentially reduces the runtime of my xstream processing script by 143 minutes.

https://github.com/superolmo/pyxtream/blob/cd9f4160bb7be7da3e0a93d2bda6ec0dbd01bd36/pyxtream/pyxtream.py#L940-L974

**Comment by superolmo** [comment]
Let me test it on my end and let you know. I believe the reason for being in there is because some providers are slow.
