### ISSUE TITLE
Start Flask

### ISSUE THREAD

**Issue by GeorgePatsias** [superolmo/pyxtream#2]
Hello I would like to know how to start the Flask API to run.

Thanks for your time.

**Comment by superolmo** [comment]
The file functional_test.py is an example of how to use it. If you are
using the library from PyPI, it is not installed by default, but you can
see/download the file from the GitHub project page at
https://github.com/superolmo/pyxtream
Let me know if you are having troubles.

**Comment by GeorgePatsias** [comment]
Can i contact you somewhere privately?

**Comment by superolmo** [comment]
My email is exposed at [https://pypi.org/project/pyxtream/](https://pypi.org/project/pyxtream/)
