### ISSUE TITLE
functional_test.py errors import moduals.

### ISSUE THREAD

**Issue by mullcom** [superolmo/pyxtream#5]
Hello. love the work here. and try to test it out but i run functionl_test.py i get some import moduals error.

i am not programmer but when i check it it seams module name is wrong?

Traceback (most recent call last):
  File "/ft.py", line 6, in <module>
    from pyxtream import XTream, __version__
  File "x/python3.11/site-packages/pyxtream/__init__.py", line 3, in <module>
    from .pyxtream import XTream
  File "x/python3.11/site-packages/pyxtream/pyxtream.py", line 31, in <module>
    from pyxtream.schemaValidator import SchemaType, schemaValidator
  File "x/python3.11/site-packages/pyxtream/schemaValidator.py", line 4, in <module>
    from jsonschema import exceptions, validate
ModuleNotFoundError: No module named 'jsonschema'

Package            Version
------------------ --------
blinker            1.7.0
certifi            2024.2.2
charset-normalizer 3.3.2
click              8.1.7
Flask              3.0.3
idna               3.7
itsdangerous       2.2.0
Jinja2             3.1.3
MarkupSafe         2.1.5
pip                23.0.1
pyxtream           0.7.0
requests           2.31.0
setuptools         66.1.1
urllib3            2.2.1
Werkzeug           3.0.2

**Comment by superolmo** [comment]
Ah, yes, I did not add the jsonschema module to the list of required packages. I need to add it.
In the meantime, from the terminal run: `pip install jsonschema`
That is the package that is missing.

**Comment by mullcom** [comment]
Thanks for the info.

Den tis 23 apr. 2024 05:03Claudio Olmi ***@***.***> skrev:
